<?php
/**
 * Copyright © fr3on. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Fr3on\Lapis\Model\Generator;

use Symfony\Component\Yaml\Yaml;

class YamlSerializer
{
    /**
     * @param array $data
     * @return string
     */
    public function serialize(array $data): string
    {
        $header = "# Generated by magento2-lapis v0.1.0\n";
        $header .= "# Resource: " . ($data['resource'] ?? 'unknown') . "\n";
        $header .= "# Generated at: " . ($data['generated'] ?? date('c')) . "\n\n";

        $yaml = Yaml::dump($data, 10, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);
        
        // Add empty line between states and transitions for readability
        $yaml = str_replace('transitions:', "\ntransitions:", $yaml);

        return $header . $yaml;
    }
}
